version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build-and-push:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - docker/check:
          docker-username: CIRCLE_PROJECT_USERNAME
          registry: ghcr.io
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: ghcr.io
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: ghcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build:
    jobs:
      - build-and-push
